api/urls.py
from django.urls import path
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

from . import views

urlpatterns = [
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    path('users/me/', views.UserDetail.as_view(), name='user_detail'),
]

modules/billing/urls.py
from django.contrib import admin
from django.urls import path, include
import modules.billing.views as views
from CONFIG.billing import BILLING_MODEL

urlpatterns = [
    path('', views.ManageBilling.as_view(), name='manage_billing'),
    path('cancel-subscription/', views.CancelSubscription.as_view(), name='cancel_subscription'),
    path('subscribe/<str:subscription_key>/', views.SubscripeToSubscription.as_view(), name='subscribe_to_subscription'),

    path('credits/purchase/<str:credit_package_key>/', views.PurchaseCreditsPackage.as_view(), name='purchase_credits_package'),
    path('credits/actions/table/data/', views.CreditActionsTableData.as_view(), name='credit_actions_table'),

     path('invoices/table/data/', views.InvoiceTableData.as_view(), name='invoice_table'),
] if BILLING_MODEL != 'none' else []

modules/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path('authentication/', include(('modules.authentication.urls', 'authentication'), namespace='authentication')),
    path('billing/', include(('modules.billing.urls', 'billing'), namespace='billing')),
    path('payments/', include(('modules.payments.urls', 'payments'), namespace='payments')),
    path('utils/', include(('modules.utils.urls', 'utils'), namespace='utils')),

    path('examples/', include(('modules.examples.urls', 'examples'), namespace='examples')),

    # Redirect the 2FA index to the user settings page
    path('accounts/2fa/', RedirectView.as_view(pattern_name='authentication:user_settings')),

    # Third-party apps
    path('accounts/', include('allauth.urls')),
    path('impersonate/', include('impersonate.urls')),
]

{{cookiecutter.project_slug}}/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.views.i18n import JavaScriptCatalog

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include(('{{ cookiecutter.main_app_name }}.urls', '{{ cookiecutter.main_app_name }}'), namespace='{{ cookiecutter.main_app_name }}')),
    path('api/', include(('api.urls', 'api'), namespace='api')),

    path('i18n/', include('django.conf.urls.i18n')), # Internationalization/translation
    path("jsi18n/", JavaScriptCatalog.as_view(), name="javascript-catalog"), # Internationalization/translation for JS
    path('swd/', include('modules.urls')), # Ship with Django
    
    path("__reload__/", include("django_browser_reload.urls")),
]

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]

modules/billing/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone

class Subscription(models.Model):

    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE, related_name='subscription')
    subscription_key = models.CharField(max_length=255)

    stripe_subscription_id = models.CharField(max_length=255, blank=True, null=True)
    stripe_status = models.CharField(max_length=255, blank=True, null=True)

    starts = models.BigIntegerField(default=0) # Unix timestamp
    current_period_start = models.BigIntegerField(default=0) # Unix timestamp
    current_period_end = models.BigIntegerField(default=0) # Unix timestamp

    cancel_at_period_end = models.BooleanField(default=False)
    lifetime = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.user} - Subscription: {self.subscription_key}"
    
    def to_dict(self):
        fields = [field.name for field in self._meta.get_fields() if field.name != 'user'] # remove the user field, as it's a ForeignKey
        methods = ['is_default', 'can_be_cancelled', 'marked_for_cancellation', 'cancels_at', 'renews_at', 'is_active']

        result = {}
        for field in fields:
            if callable(field):
                result[field] = getattr(self, field)()
            else:
                result[field] = getattr(self, field)

        for method in methods:
            result[method] = getattr(self, method)()
        
        return result
    
    def is_default(self):
        return self.subscription_key == 'default'
    
    def reset_to_default(self):
        self.subscription_key = 'default'
        self.stripe_subscription_id = None
        self.stripe_status = None
        self.starts = 0
        self.current_period_start = 0
        self.current_period_end = 0
        self.cancel_at_period_end = False
        self.save()

    def can_be_cancelled(self):
        return self.stripe_subscription_id is not None and not self.is_default() and not self.lifetime and not self.marked_for_cancellation()

    def marked_for_cancellation(self):
        return self.cancel_at_period_end and not self.lifetime and not self.is_default()
    
    def cancels_at(self):
        if self.cancel_at_period_end:
            return timezone.datetime.fromtimestamp(self.current_period_end)
        return None

    def renews_at(self):
        if self.current_period_end == 0:
            return None
        return timezone.datetime.fromtimestamp(self.current_period_end)
    
    def is_active(self):
        return self.current_period_end > timezone.now().timestamp() and self.stripe_status == 'active'
    
class StripeInvoice(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='invoices')
    stripe_id = models.CharField(max_length=255)

    number = models.CharField(max_length=255)
    hosted_invoice_url = models.URLField(null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f'{self.user} - {self.number}'
    
class CreditAction(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='credit_actions')
    amount = models.IntegerField()
    action = models.CharField(max_length=255)

    credits_before = models.IntegerField()
    credits_after = models.IntegerField()

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f'{self.user} - {self.amount} - {self.action}'

modules/billing/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

modules/billing/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import TemplateView
from django.urls import reverse
from django.contrib import messages
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.mixins import LoginRequiredMixin
from django.conf import settings

from modules.views import DynamicTableData
import modules.billing.utils as billing
from modules.billing.models import StripeInvoice, CreditAction


class InvoiceTableData(LoginRequiredMixin, DynamicTableData):
    template_name = 'billing/invoices/tables/data.html'
    model = StripeInvoice
    context_object_name = 'invoices'
    sort_options = [{ 'name': 'Number', 'field': 'number', }, { 'name': 'Date', 'field': 'created_at', }]
    sort_default = '-created_at'
    search_fields = ['number']

    def get_queryset(self):
        return self.request.user.invoices.all()
    
class CreditActionsTableData(LoginRequiredMixin, DynamicTableData):
    template_name = 'billing/credits/tables/data.html'
    model = CreditAction
    context_object_name = 'credit_actions'
    sort_options = [{ 'name': 'Date', 'field': 'created_at', }, { 'name': 'Amount', 'field': 'amount', }]
    sort_default = '-created_at'
    search_fields = ['action', 'amount']

    def get_queryset(self):
        return self.request.user.credit_actions.all()

class ManageBilling(LoginRequiredMixin, TemplateView):
    ''' Billing management page for users. '''

    template_name = 'billing/manage.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['billing_model'] = settings.BILLING_MODEL
        context['subscriptions'] = billing.SUBSCRIPTIONS
        context['credit_packages'] = billing.CREDIT_PACKAGES
        return context

class SubscripeToSubscription(LoginRequiredMixin, View):
    ''' Subscribe user to a subscription.
    
        This view is called when user clicks on the subscribe button.
    '''

    def get(self, request, *args, **kwargs):
        price_id = self.subscription_data.get('stripe_price_id')
        return redirect(reverse('payments:setup_checkout_for_price', kwargs={'price_id': price_id}))

    def dispatch(self, request, *args, **kwargs):
        subscription_key = self.kwargs.get('subscription_key')

        self.subscription_data = billing.get_subscription_by_key(subscription_key)
        if not self.subscription_data or not self.subscription_data.get('stripe_price_id'):
            messages.error(request, _('Invalid subscription key'))
            return redirect('billing:manage_billing')
        
        if subscription_key not in billing.VALID_SUBSCRIPTION_KEYS:
            messages.error(request, _('Invalid subscription key'))
            return redirect('billing:manage_billing')
        
        if subscription_key == request.user.get_subscription()['key']:
            messages.info(request, _('You are already subscribed to this subscription'))
            return redirect('billing:manage_billing')

        return super().dispatch(request, *args, **kwargs)
    
class CancelSubscription(LoginRequiredMixin, View):
    ''' Cancel user's subscription.
    
        This view is called when user clicks on the cancel subscription button.
    '''

    template_name = 'billing/subscriptions/cancel_subscription.html'

    def get(self, request, *args, **kwargs):
        context = {
            'subscription': request.user.get_subscription(),
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        subscription_cancelled = request.user.cancel_subscription()
        if subscription_cancelled:
            messages.info(request, _("You've successfully cancelled your subscription. You will not be charged again."))
        else:
            messages.error(request, _("Failed to cancel subscription. Please try again. If the problem persists, contact support."))

        return redirect('billing:manage_billing')
    
class PurchaseCreditsPackage(LoginRequiredMixin, View):
    ''' Purchase credits package.
    
        This view is called when user clicks on the purchase credits button.
    '''

    def get(self, request, *args, **kwargs):
        price_id = self.credit_package_data.get('stripe_price_id')
        return redirect(reverse('payments:setup_checkout_for_price', kwargs={'price_id': price_id}))

    def dispatch(self, request, *args, **kwargs):
        credit_package_key = self.kwargs.get('credit_package_key')

        self.credit_package_data = billing.get_credit_package_by_key(credit_package_key)
        if not self.credit_package_data:
            messages.error(request, _('Invalid price ID'))
            return redirect('billing:manage_billing')
        
        return super().dispatch(request, *args, **kwargs)

modules/billing/templates/billing/credits/credits.html
{% extends "layout/base.html" %}
{% load utils %}
{% load i18n %}

{% block title %}{% trans "Billing" %}{% endblock %}

{% block subnav %}
    {% with active='billing' %}
        {{ block.super }}
    {% endwith %}
{% endblock %}

{% block content %}

<div class="mb-6">
    <div class="flex items-center">
        <i class="text-2xl text-gray-700 mr-2" data-feather="credit-card"></i>
        <h1 class="text-2xl font-semibold text-default">{% trans "Billing" %}</h1>
    </div>
</div>

{% include 'billing/credits/page_content.html' %}

<div class="mt-12 bg-white shadow-sm border rounded-2xl group">
    <div class="flex items-center justify-between p-4 border-b">
        <h2 class="text-lg font-semibold flex items-center">
            {% trans "Your invoices" %}
        </h2>
    </div>
    <div class="p-4">
        <table class="dynamic" data-url="{% url 'billing:invoice_table' %}"></table>
    </div>
</div>

{% endblock %}

modules/billing/templates/billing/credits/page_content.html
{% load utils %}
{% load i18n %}

{% with balance=request.user.credits_balance %}

<div class="my-6 bg-white shadow-sm border rounded-2xl group">
    <div class="flex items-center justify-between p-4 border-b">
        <h2 class="text-lg font-semibold flex items-center">
            {% trans "Your balance" %}
        </h2>
    </div>

    <div class="p-4 flex items-center group-hover:bg-slate-50">
        <div class="flex-shrink-0 w-12 h-12 bg-blue-100 text-blue-600 flex items-center justify-center rounded-2xl">
            <i data-feather="box" class="w-6 h-6"></i>
        </div>
        <div class="ml-4">
            <h3 class="text-lg font-semibold">{{ balance }} credits</h3>
            <p class="text-sm text-gray-600">{% trans "You can use these credits for a variety of actions on our platform" %}</p>
        </div>
    </div>


</div>

<div class="mt-12">
    <h2 class="text-xl font-semibold flex items-center">
        {% trans "Buy credits" %}
    </h2>
    <p class="text-sm text-gray-600 mt-2">
        {% trans "Top up your balance with credits and enjoy our services." %}
    </p>
</div>

{% for package in credit_packages %}
    {% if package.show %}
    <div class="my-4 bg-white shadow-sm border rounded-2xl">
        <div class="p-4 flex flex-col lg:flex-row items-center hover:bg-slate-50">
            <div class="flex-shrink-0 w-12 h-12 bg-blue-100 text-blue-600 flex items-center justify-center rounded-2xl">
                <i data-feather="{{ package.icon }}" class="w-6 h-6"></i>
            </div>
            <div class="ml-0 lg:ml-4 mt-2 lg:mt-0">
                <h3 class="text-lg font-semibold text-center lg:text-left">{{ package.name }}</h3>
                <p class="text-sm text-gray-600 text-center lg:text-left">{{ package.description }}</p>
            </div>
            <div class="mt-2 lg:mt-0 lg:ml-auto w-full lg:w-auto">
                <a href="{% url 'billing:purchase_credits_package' package.key %}" class="bg-primary text-white px-4 py-2 rounded-2xl focus:outline-none text-sm font-semibold block text-center lg:inline-block">
                    {% trans "Get it for" %} {{ package.price.currency_symbol }} {{ package.price.value|floatformat:2 }} <i class="ml-1 inline" data-feather="arrow-right" width="14px" height="14px"></i>
                </a>
            </div>
        </div>
    </div>
    {% endif %}
{% endfor %}

{% endwith %}