api/urls.py
from django.urls import path
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

from . import views

urlpatterns = [
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    path('users/me/', views.UserDetail.as_view(), name='user_detail'),
]

modules/billing/urls.py
from django.contrib import admin
from django.urls import path, include
import modules.billing.views as views
from CONFIG.billing import BILLING_MODEL

urlpatterns = [
    path('', views.ManageBilling.as_view(), name='manage_billing'),
    path('cancel-subscription/', views.CancelSubscription.as_view(), name='cancel_subscription'),
    path('subscribe/<str:subscription_key>/', views.SubscripeToSubscription.as_view(), name='subscribe_to_subscription'),

    path('credits/purchase/<str:credit_package_key>/', views.PurchaseCreditsPackage.as_view(), name='purchase_credits_package'),
    path('credits/actions/table/data/', views.CreditActionsTableData.as_view(), name='credit_actions_table'),

     path('invoices/table/data/', views.InvoiceTableData.as_view(), name='invoice_table'),
] if BILLING_MODEL != 'none' else []

modules/examples/urls.py
from django.contrib import admin
from django.urls import path, include


from . import views

urlpatterns = [

    path('email/', views.EmailExample.as_view(), name='email'),

    path('credits/', views.CreditsExample.as_view(), name='credits'),
    path('credits/action/post/', views.CreditsActionExamplePOST.as_view(), name='credits_action_post'),
    path('credits/action/get/', views.CreditsActionExampleGET.as_view(), name='credits_action_get'),

    path('excel/', views.ExcelExample.as_view(), name='excel'),
    path('excel/export/', views.ExcelExportExample.as_view(), name='excel_export'),

    path('pdf/', views.PDFExample.as_view(), name='pdf'),
    path('pdf/export/', views.PDFExportExample.as_view(), name='pdf_export'),

    path('tables/', views.ExampleModelTable.as_view(), name='tables'),
    path('tables/data/', views.ExampleModelTableData.as_view(), name='tables_data'),

    path('websockets/', views.WebsocketsExample.as_view(), name='websockets'),

    path('file-generate/', views.LargeFileGenerateExample.as_view(), name='file_generate'),
    path('file-generate/start/', views.LargeFileGenerateStartTask.as_view(), name='file_generate_start_task'),

    path('form-wizard/', views.FormWizardExample.as_view(), name='form_wizard'),

    path('dall-e/', views.OpenAIDallEExample.as_view(), name='dall_e'),

]

modules/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path('authentication/', include(('modules.authentication.urls', 'authentication'), namespace='authentication')),
    path('billing/', include(('modules.billing.urls', 'billing'), namespace='billing')),
    path('payments/', include(('modules.payments.urls', 'payments'), namespace='payments')),
    path('utils/', include(('modules.utils.urls', 'utils'), namespace='utils')),

    path('examples/', include(('modules.examples.urls', 'examples'), namespace='examples')),

    # Redirect the 2FA index to the user settings page
    path('accounts/2fa/', RedirectView.as_view(pattern_name='authentication:user_settings')),

    # Third-party apps
    path('accounts/', include('allauth.urls')),
    path('impersonate/', include('impersonate.urls')),
]

websockets/urls.py
from django.urls import path
from . import views

urlpatterns = [
]

{{cookiecutter.project_slug}}/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.views.i18n import JavaScriptCatalog

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include(('{{ cookiecutter.main_app_name }}.urls', '{{ cookiecutter.main_app_name }}'), namespace='{{ cookiecutter.main_app_name }}')),
    path('api/', include(('api.urls', 'api'), namespace='api')),

    path('i18n/', include('django.conf.urls.i18n')), # Internationalization/translation
    path("jsi18n/", JavaScriptCatalog.as_view(), name="javascript-catalog"), # Internationalization/translation for JS
    path('swd/', include('modules.urls')), # Ship with Django
    
    path("__reload__/", include("django_browser_reload.urls")),
]

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]

modules/examples/models.py
from django.db import models

class ExampleModel(models.Model):
    name = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    note = models.TextField()

    def __str__(self):
        return self.name

modules/examples/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from modules.forms import FormWithPlaceholders

class SendTestEmailForm(FormWithPlaceholders):
    to_email = forms.EmailField(label=_('To Email Address'))

    class Meta:
        placeholders = {
            'to_email' : _('Fill in your email address'),
        }

class ConsumeCreditForm(FormWithPlaceholders):
    amount = forms.IntegerField(label=_('Amount'))
    action = forms.CharField(label=_('Action'))

    class Meta:
        placeholders = {
            'amount' : _('Amount of credits to consume'),
            'action' : _('The reason for consuming the credits'),
        }

class GenerateImageForm(FormWithPlaceholders):
    prompt = forms.CharField(label=_('Prompt'), widget=forms.Textarea)
    size = forms.ChoiceField(label=_('Size'), choices=[('1024x1024', '1024x1024'), ('1024x1792', '1024x1792'), ('1792x1024', '1792x1024')])
    quality = forms.ChoiceField(label=_('Quality'), choices=[('standard', 'Standard'), ('hd', 'HD')])

    class Meta:
        placeholders = {
            'prompt' : _('The prompt to generate the image from'),
            'size' : _('The size of the image to generate'),
            'quality' : _('The quality of the image to generate'),
        }

modules/examples/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import FormView, TemplateView, View
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.utils import timezone
from django.http import JsonResponse

from modules.emails.utils import send_email_from_base_template
from modules.billing.mixins import CreditActionMixin
from modules.views import ExcelModelExport, PDFExport, DynamicTableData
from modules.ai.openai import generate_image

from .seeder import ExampleSeeder
from .forms import SendTestEmailForm, ConsumeCreditForm, GenerateImageForm
from .models import ExampleModel
from .tasks import generate_large_file

## Example: Email
class EmailExample(LoginRequiredMixin, FormView):

    template_name = 'examples/email.html'
    form_class = SendTestEmailForm

    def form_valid(self, form):
        to_email = form.cleaned_data['to_email']
        send_email_from_base_template(
            to_emails=to_email,
            subject='Test Email',
            template_data = {
                'heading' : 'Test Email',
                'subheading' : 'This is a test email from ShipWithDjango',
                'content' : 'This is a test email from ShipWithDjango. If you received this email, it means that the email functionality is working correctly.',
                'buttons' : [
                    {
                        'text' : 'Go to Docs',
                        'url' : 'https://www.shipwithdjango.com',
                    }
                ]
            }
        )

        return super().form_valid(form)
    
    def get_success_url(self):
        messages.success(self.request, _('Test email sent successfully'))
        return reverse('examples:email')

## Example: Credits
class CreditsExample(LoginRequiredMixin, FormView):

    template_name = 'examples/credits.html'
    form_class = ConsumeCreditForm

    def form_valid(self, form):
        amount = form.cleaned_data['amount']
        action = form.cleaned_data['action']

        if self.request.user.has_credits(amount):
            self.request.user.consume_credits(amount, action)
            messages.success(self.request, _('Credits consumed successfully'))
        else:
            messages.error(self.request, _('You do not have enough credits to perform this action'))

        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse('examples:credits')
    
class CreditsActionExamplePOST(CreditActionMixin, TemplateView):
    amount_of_credits = 5
    action = 'You consumed 5 credits (POST action)'
    consume_credits_on = 'POST'

    template_name = 'examples/credits_action.html'

    def get_failed_url(self):
        messages.error(self.request, _('You do not have enough credits to perform this action'))
        return reverse('examples:credits')
    
    def get_success_url(self):
        messages.success(self.request, _('Credits consumed successfully'))
        return reverse('examples:credits')
    
class CreditsActionExampleGET(CreditActionMixin, View):
    amount_of_credits = 5
    action = 'You consumed 5 credits (GET action)'
    consume_credits_on = 'GET'

    def get_failed_url(self):
        messages.error(self.request, _('You do not have enough credits to perform this action'))
        return reverse('examples:credits')

    def get_success_url(self):
        messages.success(self.request, _('Credits consumed successfully'))
        return reverse('examples:credits')

## Example: Excel export
class ExcelExample(LoginRequiredMixin, TemplateView):
    template_name = 'examples/excel.html'

class ExcelExportExample(ExcelModelExport):
    model = get_user_model()

    # You can pass fields as a list of strings or a list of dictionaries
    # If you pass a list of strings, the header will be the field name
    # If you pass a list of dictionaries, you can specify the header and the field name

    # fields = ['id', 'username', 'first_name', 'last_name', 'email', 'last_login', 'date_joined', 'is_active']
    fields = [
        {'header' : 'id', 'field': 'id' },
        {'header' : 'Username', 'field': 'username' },
        {'header' : 'First Name', 'field': 'first_name' },
        {'header' : 'Last Name', 'field': 'last_name' },
        {'header' : 'Email', 'field': 'email' },
        {'header' : 'Last Login', 'field': 'last_login' },
        {'header' : 'Date Joined', 'field': 'date_joined' },
        {'header' : 'Is Active', 'field': 'is_active' },
    ]

## Example: PDF export
class PDFExample(LoginRequiredMixin, TemplateView):
    template_name = 'examples/pdf.html'

class PDFExportExample(PDFExport):
    template_name = 'examples/pdf_file_template.html'
    
    def get_context(self, request, *args, **kwargs):
        return {
            'current_user' : request.user,
            'generated_at' : timezone.now(),
            'heading' : 'PDF Export Example',
            'subheading' : 'This is a PDF export example from ShipWithDjango',
            'content' : 'This is a PDF export example from ShipWithDjango. If you downloaded this PDF, it means that the PDF export functionality is working correctly.',
        }

## Example: Table with server-side processing
class ExampleModelTable(LoginRequiredMixin, TemplateView):
    template_name = 'examples/tables/tables.html'

    def post(self, request, *args, **kwargs):
        seeder = ExampleSeeder(count=200)
        seeder.clear()
        seeder.run()
        messages.success(request, _('Example data seeded successfully'))
        return super().get(request, *args, **kwargs)

class ExampleModelTableData(LoginRequiredMixin, DynamicTableData):
    template_name = 'examples/tables/data.html'
    model = ExampleModel
    context_object_name = 'example_models'
    sort_options = [{ 'name': 'Name', 'field': 'name', }, { 'name': 'Address', 'field': 'address', }]
    sort_default = 'name'
    search_fields = ['name', 'address']

    def get_queryset(self):
        return ExampleModel.objects.all()
    
## Example: Xebsockets
class WebsocketsExample(LoginRequiredMixin, TemplateView):
    template_name = 'examples/websockets.html'

## Example: File generation with tasks
class LargeFileGenerateExample(LoginRequiredMixin, TemplateView):
    template_name = 'examples/large_file_generate.html'

class LargeFileGenerateStartTask(LoginRequiredMixin, View):

    def post(self, request, *args, **kwargs):
        task = generate_large_file()
        return JsonResponse({'task_id': task.id})

## Example: Form wizard
class FormWizardExample(LoginRequiredMixin, TemplateView):
    template_name = 'examples/form_wizard.html'

## Example: OpenAI Dall-E
class OpenAIDallEExample(LoginRequiredMixin, FormView):
    template_name = 'examples/openai_dalle.html'
    form_class = GenerateImageForm

    def form_valid(self, form):
        prompt = form.cleaned_data['prompt']
        size = form.cleaned_data['size']
        quality = form.cleaned_data['quality']
        image = generate_image(prompt, size, quality)
        return JsonResponse({'base64_image': image})

modules/websockets/views.py
from .consumers import ShipWithDjangoConsumer

class ExampleConsumer(ShipWithDjangoConsumer):
    channel_groups = ['examples']

    async def receive_event(self, event, page_id, user, response):

        if event == 'ping':
            await self.send_to_all_groups(
                action='show_message',
                page_id=page_id,
                payload= {
                    'message': 'pong'
                }
            )
        elif event == 'greeting':
            await self.send_to_all_groups(
                action='show_message',
                page_id=page_id,
                payload= {
                    'message': 'Hello, ' + user.get_full_name()
                }
            )
        else:
            await self.send_to_all_groups(
                action='error',
                page_id=page_id,
                payload= {
                    'message': 'Invalid event'
                }
            )

class UserConsumer(ShipWithDjangoConsumer):
    channel_groups = ['users', 'user_{user.id}']

    async def receive_event(self, event, page_id, user, response):
        await self.send_to_all_groups(
            action='error',
            page_id=page_id,
            payload= {
                'message': 'Invalid event'
            }
        )

modules/examples/templates/examples/credits.html
{% extends "layout/base.html" %}
{% load i18n %}

{% block title %}{% trans "Credits" %}{% endblock %}

{% block subnav %}
    {% with active='example_credits' %}
        {{ block.super }}
    {% endwith %}
{% endblock %}

{% block content %}

<div class="mb-6">
    <div class="flex items-center">
        <i class="text-2xl text-gray-700 mr-2" data-feather="box"></i>
        <h1 class="text-2xl font-semibold text-default">{% trans "Credits" %}</h1>
    </div>
    <div>
    <p class="text-gray-500">
        {% trans "Let users buy credits and use them for a variety of actions on your platform." %}
        <br/>{% trans "<b>Where can I find the template of this page?</b> You can find this template at" %} <code class="bg-gray-100 text-gray-700 p-1 rounded-2xl">shipwithdjango/examples/templates/examples/credits.html</code>.
        <br/>{% trans "<b>Where can I find the backend logic of this page?</b> You can find the view" %} <code class="bg-gray-100 text-gray-700 p-1 rounded-2xl">CreditsExample</code> {% trans "at" %} <code class="bg-gray-100 text-gray-700 p-1 rounded-2xl">shipwithdjango/examples/views.py</code>.
    </p>
    </div>
</div>

<div class="bg-white shadow-sm border rounded-2xl p-8">
    <div class="flex flex-col items-center justify-center">
        <div class="w-24 h-24 bg-primary-light rounded-full flex items-center justify-center mb-4 text-primary">
            <i data-feather="box"></i>
        </div>
        <h3 class="text-lg font-semibold mb-2">{% trans "Consume credits" %}</h3>
        <p class="text-gray-600 text-center mb-6">
            {% trans "You can easily integrate a credit system in your platform. Users can buy credits and use them for a variety of actions." %}
            <br/>{% trans "Users can check and top up their balance on the 'Billing' page." %}
        </p>
        <p class="text-gray-600 text-center mb-6">
            {% trans "When a user performs an action, you can deduct credits and log the transaction." %}
            <br/>{% trans "Be sure to set your billing configuration first in" %} <code class="bg-gray-100 text-gray-700 p-1 rounded-2xl">CONFIG/billing.py</code>.
        </p>

        <form method="POST">
            {% csrf_token %}
            {{ form.amount.as_field_group }}
            {{ form.action.as_field_group }}
            <button type="submit" class="w-full bg-primary text-white py-2 rounded-2xl focus:outline-none font-semibold">{% trans "Consume credits" %}</button>
        </form>
    </div>
</div>

<div class="mt-12 bg-white shadow-sm border rounded-2xl group">
    <div class="flex items-center justify-between p-4 border-b">
        <h2 class="text-lg font-semibold flex items-center">
            {% trans "Your credit actions" %}
        </h2>
    </div>
    <div class="p-4">
        <table class="dynamic" data-url="{% url 'billing:credit_actions_table' %}"></table>
    </div>
</div>

<div class="mt-12 bg-white shadow-sm border rounded-2xl p-8">
    <div class="flex flex-col items-center justify-center">
        <h3 class="text-lg font-semibold mb-2">{% trans "Perform an action" %}</h3>
        <p class="text-gray-600 text-center mb-6">
            {% trans "Click on the buttons below to perform an action that will consume credits." %}
        </p>

        <div class="flex gap-3">
            <button @click="$dispatch('opendynamicmodal', { 'url' : '{% url "examples:credits_action_post" %}' })" class="bg-primary text-white px-4 py-2 rounded-2xl focus:outline-none text-sm font-semibold block text-center lg:inline-block">
                {% trans "Perform action on POST" %}
            </button>

            <a href="{% url "examples:credits_action_get" %}" class="bg-primary text-white px-4 py-2 rounded-2xl focus:outline-none text-sm font-semibold block text-center lg:inline-block">
                {% trans "Perform action on GET" %}
            </a>
        </div>

    </div>
</div>

{% endblock %}

modules/examples/templates/examples/credits_action.html
{% load i18n %}

<form action="{% url 'examples:credits_action_post' %}" method="post">
{% csrf_token %}
<div class="flex flex-col space-y-5">
    <h1 class="text-xl font-medium text-gray-800 ">{% trans "You're about to consume 5 credits" %}</h1>
    <p class="text-gray-600">
        {% trans "You are about to consume 5 credits. This action will be logged." %}
    </p>
    <button type="submit" class="bg-primary text-white px-4 py-2 rounded-2xl focus:outline-none text-sm font-semibold block text-center lg:inline-block">{% trans "Consume credits" %}</button>
</div>
</form>

modules/examples/templates/examples/email.html
{% extends "layout/base.html" %}
{% load i18n %}

{% block title %}{% trans "Email" %}{% endblock %}

{% block subnav %}
    {% with active='example_email' %}
        {{ block.super }}
    {% endwith %}
{% endblock %}

{% block content %}

<div class="mb-6">
    <div class="flex items-center">
        <i class="text-2xl text-gray-700 mr-2" data-feather="mail"></i>
        <h1 class="text-2xl font-semibold text-default">{% trans "Email" %}</h1>
    </div>
    <div>
    <p class="text-gray-500">
        {% trans "Email is a powerful tool for sending messages to users." %}
        <br/>{% trans "<b>Where can I find the template of this page?</b> You can find this template at" %} <code class="bg-gray-100 text-gray-700 p-1 rounded-2xl">shipwithdjango/examples/templates/examples/email.html</code>.
        <br/>{% trans "<b>Where can I find the backend logic of this page?</b> You can find the view" %} <code class="bg-gray-100 text-gray-700 p-1 rounded-2xl">EmailExample</code> {% trans "at" %} <code class="bg-gray-100 text-gray-700 p-1 rounded-2xl">shipwithdjango/examples/views.py</code>.
    </p>
    </div>
</div>

<div class="bg-white shadow-sm border rounded-2xl p-8">
    <div class="flex flex-col items-center justify-center">
        <div class="w-24 h-24 bg-primary-light rounded-full flex items-center justify-center mb-4 text-primary">
            <i data-feather="send"></i>
        </div>
        <h3 class="text-lg font-semibold mb-2">{% trans "Send a test email" %}</h3>
        <p class="text-gray-600 text-center mb-6">
            {% trans "See how email looks like in your inbox. Ship with Django comes with a pre-made HTML email template." %}
            <br/>{% trans "You can choose to send emails asynchronously using the task queue or synchronously." %}
            <br/>{% trans "Be sure to set your email configuration first in" %} <code class="bg-gray-100 text-gray-700 p-1 rounded-2xl">CONFIG/emails.py</code>.
        </p>

        <form method="POST">
            {% csrf_token %}
            {{ form.to_email.as_field_group }}
            <button type="submit" class="w-full bg-primary text-white py-2 rounded-2xl focus:outline-none font-semibold">{% trans "Send test email" %}</button>
        </form>
    </div>
</div>

{% endblock %}

modules/examples/templates/examples/excel.html
{% extends "layout/base.html" %}
{% load i18n %}

{% block title %}{% trans "Excel export" %}{% endblock %}

{% block subnav %}
    {% with active='example_excel' %}
        {{ block.super }}
    {% endwith %}
{% endblock %}

{% block content %}

<div class="mb-6">
    <div class="flex items-center">
        <i class="text-2xl text-gray-700 mr-2" data-feather="file"></i>
        <h1 class="text-2xl font-semibold text-default">{% trans "Excel export" %}</h1>
    </div>
    <div>
    <p class="text-gray-500">
        {% trans "Useful for generating reports or sharing data with users." %}
        <br/>{% trans "<b>Where can I find the template of this page?</b> You can find this template at" %} <code class="bg-gray-100 text-gray-700 p-1 rounded-2xl">shipwithdjango/examples/templates/examples/excel.html</code>.
        <br/>{% trans "<b>Where can I find the backend logic of this page?</b> You can find the view" %} <code class="bg-gray-100 text-gray-700 p-1 rounded-2xl">ExcelExample</code> {% trans "at" %} <code class="bg-gray-100 text-gray-700 p-1 rounded-2xl">shipwithdjango/examples/views.py</code>.
    </p>
    </div>
</div>

<div class="bg-white shadow-sm border rounded-2xl p-8">
    <div class="flex flex-col items-center justify-center">
        <div class="w-24 h-24 bg-primary-light rounded-full flex items-center justify-center mb-4 text-primary">
            <i data-feather="file"></i>
        </div>
        <h3 class="text-lg font-semibold mb-2">{% trans "Export data to an Excel file" %}</h3>
        <p class="text-gray-600 text-center mb-6">
            {% trans "You can easily export data to an Excel file from any given queryset. This is useful for generating reports or sharing data with users." %}
        </p>
        <p>
            <a href="{% url "examples:excel_export" %}" class="bg-primary text-white px-4 py-2 rounded-2xl focus:outline-none text-sm font-semibold block text-center lg:inline-block">
                {% trans "Download Excel example" %}
            </a>
        </p>

    </div>
</div>

{% endblock %}

modules/examples/templates/examples/pdf.html
{% extends "layout/base.html" %}
{% load i18n %}

{% block title %}{% trans "PDF export" %}{% endblock %}

{% block subnav %}
    {% with active='example_pdf' %}
        {{ block.super }}
    {% endwith %}
{% endblock %}

{% block content %}

<div class="mb-6">
    <div class="flex items-center">
        <i class="text-2xl text-gray-700 mr-2" data-feather="file-text"></i>
        <h1 class="text-2xl font-semibold text-default">{% trans "PDF export" %}</h1>
    </div>
    <div>
    <p class="text-gray-500">
        {% trans "Useful for generating reports or sharing data with users." %}
        <br/>{% trans "<b>Where can I find the template of this page?</b> You can find this template at" %} <code class="bg-gray-100 text-gray-700 p-1 rounded-2xl">shipwithdjango/examples/templates/examples/pdf.html</code>.
        <br/>{% trans "<b>Where can I find the backend logic of this page?</b> You can find the view" %} <code class="bg-gray-100 text-gray-700 p-1 rounded-2xl">PDFExample</code> {% trans "at" %} <code class="bg-gray-100 text-gray-700 p-1 rounded-2xl">shipwithdjango/examples/views.py</code>.
    </p>
    </div>
</div>

<div class="bg-white shadow-sm border rounded-2xl p-8">
    <div class="flex flex-col items-center justify-center">
        <div class="w-24 h-24 bg-primary-light rounded-full flex items-center justify-center mb-4 text-primary">
            <i data-feather="file"></i>
        </div>
        <h3 class="text-lg font-semibold mb-2">{% trans "Export data to a PDF file" %}</h3>
        <p class="text-gray-600 text-center mb-6">
            {% trans "You can easily generate a PDF file from any HTML template and use Django templating to fill in the data. This is useful for generating reports or sharing data with users." %}
        </p>
        <p>
            <a href="{% url 'examples:pdf_export' %}" class="bg-primary text-white px-4 py-2 rounded-2xl focus:outline-none text-sm font-semibold block text-center lg:inline-block">
                {% trans "Download PDF example" %}
            </a>
        </p>

    </div>
</div>

{% endblock %}

modules/examples/templates/examples/pdf_file_template.html
<html>
    <head>
        <style type="text/css">
            * {
                font-family: Arial, Helvetica, sans-serif;
                font-size: 12px;
                line-height: 1.5;
            }

            @page {
                size: a4 portrait;
                margin: 1cm;

                @frame footer_frame {     
                    -pdf-frame-content: footer;
                    left: 50pt; width: 512pt; top: 680pt;height: 500pt;
                }

                @top-right{
                    content: "Page " counter(page) " of " counter(pages);
                }
            }
        </style>
    </head>
    <body>
        <h1>PDF export</h1>
        <small>Generated by {{ current_user.get_full_name }} on {{ generated_at|date:'d/m/Y H:i:s' }}</small>

        <h2>{{ heading }}</h2>
        <h4>{{ subheading }}</h4>
        <p>
            {{ content }}
        </p>
    </body>
</html>